### ISSUE TITLE
Endpoint na API para listar arquivos de um dataset

### ISSUE THREAD

**Issue by berinhard** [turicas/brasil.io#458]
Agora que temos a rota `/dataset/covid19/files/` por exemplo, podemos criar também um endpoint na API para serializar as URLs dos arquivos de um dataset. Exemplo da resposta:

```json
[
  {
    "file_url": "url_do_arquivo.csv.gz",
    "sha512sum": "fcb26589e69f1709738dfe4877e09ead6e43a5480d016b09ce81d31f8113fa2b8d486b53275aaec805a6221403d2fdc47a7c3729df54dbda3809863832a325a4",
    "filename": "arquivo.csv.gz",
    "size": 1234123,
    "created_at": "data da criação"
  },
]
```

**TODO**:

- [ ] Criar rota: `/api/dataset/<slug>/files/`;
- [ ] Serializar nova rota na listagem e detalhe de um dataset;
- [ ] Atualizar 429 para adicionar a rota para a pessoa conseguir baixar os arquivos via API;

**Comment by lucassalaz4r** [comment]
Em que consiste atualizar o 429? Confesso que não entendi muito bem.
